## Manipulación de Datos 

Una de las tareas más importantes en el Análisis de Datos es la manipulación de datos tabulares. Python posee una biblioteca denominada pandas que provee de estructuras de datos y funciones diseñadas para trabajar de manera rápida, fácil y expresiva con datos estructurados. Este es considerado uno de los elementos críticos que permiten que Python sea un ambiente de análisis de datos productivo y poderoso.

Este cuaderno es una adaptación del curso de dplyr de Hadley Wickham. 

#### pandas
Biblioteca de python que permite manipular estructuras de datos llamados DataFrame. Bibliotecas "cercanas" a pandas son numpy(matrices), xarray(tensores con 'coordenadas'), pytorch (tensores en GPUs), sklearn(algoritmos de ML). La mejor manera de aprenderlo es hacer ejercicios. 


#### Datos que usaremos (usaras) 
* Descarga los datos estan en el repositorio 
* Contiene: 
    * Todos los vuelos partiendo de Houston en 2011 (flights.csv)
    * Datos de clima por hora (weather.csv)
    * Metadatos de aviones y aeropuertos (planes.csv y airports.csv)

### 1. Leer Datos 

Los datos pueden almacenarse en diferentes formas y formatos. Una de las más empleadas son los archivos CSV, cuyas siglas provienen de Comma-Separated Value files, es decir, archivos con valores separados por coma. Este archivo contiene usualmente en la primera línea el encabezado de las columnas y a partir de la segunda los registros correspondientes en el cual los datos por columna se encuentran separados por una coma. 

El objeto principal en pandas se denomina DataFrame el cual es una estructura tabular bidimensional que permite almacenar datos de diferente tipo en forma de columnas. La estructura del DataFrame es similar a las hojas de cálculo.

In [3]:
import pandas as pd 
from pathlib import Path 

raw_dir = Path('flights')
flights = pd.read_csv(raw_dir/'flights.csv')

In [4]:
type(flights)

pandas.core.frame.DataFrame

In [5]:
flights

,date,hour,minute,dep,arr,dep_delay,arr_delay,carrier,flight,dest,plane,cancelled,time,dist
0,2011-01-01 12:00:00,14.0,0.0,1400.0,1500.0,0.0,-10.0,AA,428,DFW,N576AA,0,40.0,224
1,2011-01-02 12:00:00,14.0,1.0,1401.0,1501.0,1.0,-9.0,AA,428,DFW,N557AA,0,45.0,224
2,2011-01-03 12:00:00,13.0,52.0,1352.0,1502.0,-8.0,-8.0,AA,428,DFW,N541AA,0,48.0,224
3,2011-01-04 12:00:00,14.0,3.0,1403.0,1513.0,3.0,3.0,AA,428,DFW,N403AA,0,39.0,224
4,2011-01-05 12:00:00,14.0,5.0,1405.0,1507.0,5.0,-3.0,AA,428,DFW,N492AA,0,44.0,224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227491,2011-12-06 12:00:00,18.0,18.0,1818.0,2111.0,8.0,-9.0,WN,1191,TPA,N284WN,0,97.0,781
227492,2011-12-06 12:00:00,20.0,47.0,2047.0,2334.0,7.0,4.0,WN,1674,TPA,N366SW,0,94.0,781
227493,2011-12-06 12:00:00,9.0,12.0,912.0,1031.0,-3.0,-4.0,WN,127,TUL,N777QC,0,61.0,453
227494,2011-12-06 12:00:00,6.0,56.0,656.0,812.0,-4.0,-13.0,WN,621,TUL,N727SW,0,64.0,453
227495,2011-12-06 12:00:00,16.0,0.0,1600.0,1713.0,0.0,-12.0,WN,1597,TUL,N745SW,0,59.0,453

#### EJERCICIO EN CLASE: 
¿Qué preguntas te gustarían hacer con estos datos?

#### 1.1  Atributos y Métodos del DataFrame

Los objetos en el contexto de programación orientada a objetos tiene dos elementos asociados con ellos, los atributos y los métodos. 
* Atributos:características de los objetos
* Métodos: funcionalidades asociados a los objetos

En Python, es posible acceder a un atributo attribute de un objeto object mediante la sentencia object.attribute. Por otro lado, un método method() puede ser llamado empleando object.method() y proporcionando los argumentos relacionados con él. Por ejemplo, el título (title) del objeto libro (book) se accedería mediante book.title; mientras que la acción de abrir el libro (open()) se realizaría mediante book.open(). Utilicemos los métodos y atributos que provee el objeto DataFrame para explorar nuestros datos. El contenido del DataFrame puede ser accedido mediante los métodos head() y tail(). Estos proveen, respectivamente, la impresión de las primeras y cinco últimas líneas del dataframe. Si deseas ver más líneas, puedes proporcionar el número deseado como argumento de los métodos.

In [8]:
flights.head()

,date,hour,minute,dep,arr,dep_delay,arr_delay,carrier,flight,dest,plane,cancelled,time,dist
0,2011-01-01 12:00:00,14.0,0.0,1400.0,1500.0,0.0,-10.0,AA,428,DFW,N576AA,0,40.0,224
1,2011-01-02 12:00:00,14.0,1.0,1401.0,1501.0,1.0,-9.0,AA,428,DFW,N557AA,0,45.0,224
2,2011-01-03 12:00:00,13.0,52.0,1352.0,1502.0,-8.0,-8.0,AA,428,DFW,N541AA,0,48.0,224
3,2011-01-04 12:00:00,14.0,3.0,1403.0,1513.0,3.0,3.0,AA,428,DFW,N403AA,0,39.0,224
4,2011-01-05 12:00:00,14.0,5.0,1405.0,1507.0,5.0,-3.0,AA,428,DFW,N492AA,0,44.0,224

In [11]:
flights.shape

(227496, 14)

Acá vemos que nuestro data frame tiene 14 columnas y 2227496 renglones.

In [13]:
# Tamaño: número de celdas
flights.size

3184944

In [14]:
# Información del data frame: acá vemos el nombre de las columnas y el tipo
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227496 entries, 0 to 227495
Data columns (total 14 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   date       227496 non-null  object
 1   hour       224591 non-null  float64
 2   minute     224591 non-null  float64
 3   dep        224591 non-null  float64
 4   arr        224430 non-null  float64
 5   dep_delay  224591 non-null  float64
 6   arr_delay  223874 non-null  float64
 7   carrier    227496 non-null  object
 8   flight     227496 non-null  int64
 9   dest       227496 non-null  object
 10  plane      226701 non-null  object
 11  cancelled  227496 non-null  int64
 12  time       223874 non-null  float64
 13  dist       227496 non-null  int64
dtypes: float64(7), int64(3), object(4)
memory usage: 24.3+ MB

#### ¿Qué tipo de variables tenemos?

In [16]:
print("Columnas: ")
print(flights.columns, '\n')
print("Índices: ")
print(flights.index)

Columnas:
Index(['date', 'hour', 'minute', 'dep', 'arr', 'dep_delay', 'arr_delay',
       'carrier', 'flight', 'dest', 'plane', 'cancelled', 'time', 'dist'],
      dtype='object')

Índices:
RangeIndex(start=0, stop=227496, step=1)

In [17]:
# Tipo de variables 
flights.dtypes

date          object
hour         float64
minute       float64
dep          float64
arr          float64
dep_delay    float64
arr_delay    float64
carrier       object
flight         int64
dest          object
plane         object
cancelled      int64
time         float64
dist           int64
dtype: object

### 2. Indices

¿Qué operaciones quiero hacer con los datos? ¿Cómo los quiero escribir?
Los DataFrame en pandas tienen dos ejes(axis) de indices: columnas y renglones.
Para este ejemplo vamos a usar la base de datos de los aviones `planes.csv`

In [19]:
#1. ¿Cómo se ve esta base?
planes = pd.read_csv(raw_dir/'planes.csv')
planes

,plane,year,mfr,model,no.eng,no.seats,speed,engine,type
0,N576AA,1991.0,MCDONNELL DOUGLAS,DC-9-82(MD-82),2.0,172,NaN,Turbo-fan,Fixed wing multi engine
1,N557AA,1993.0,MARZ BARRY,KITFOX IV,1.0,2,NaN,Reciprocating,Fixed wing single engine
2,N403AA,1974.0,RAVEN,S55A,NaN,1,60.0,None,Balloon
3,N492AA,1989.0,MCDONNELL DOUGLAS,DC-9-82(MD-82),2.0,172,NaN,Turbo-fan,Fixed wing multi engine
4,N262AA,1985.0,MCDONNELL DOUGLAS,DC-9-82(MD-82),2.0,172,NaN,Turbo-fan,Fixed wing multi engine
...,...,...,...,...,...,...,...,...,...
2848,N647AW,1997.0,AIRBUS INDUSTRIE,A320-232,2.0,200,NaN,Turbo-fan,Fixed wing multi engine
2849,N637AW,1990.0,AIRBUS INDUSTRIE,A320-231,2.0,182,NaN,Turbo-jet,Fixed wing multi engine
2850,N676AW,2005.0,AIRBUS,A320-232,2.0,200,NaN,Turbo-fan,Fixed wing multi engine
2851,N642AW,1996.0,AIRBUS INDUSTRIE,A320-232,2.0,200,NaN,Turbo-fan,Fixed wing multi engine
2852,N624AW,1989.0,AIRBUS INDUSTRIE,A320-231,2.0,182,NaN,Turbo-jet,Fixed wing multi engine

In [22]:
#2. Definir los indices. En este caso el número del avión
planes = planes.set_index(pd.CategoricalIndex(planes['plane'], name = 'identifier'))
## tiramos la columna original del numero de avión
planes = planes.drop('plane', axis = 'columns')

In [23]:
#3. Explorar esta base 
print(planes.columns)
print(planes.index)

Index(['year', 'mfr', 'model', 'no.eng', 'no.seats', 'speed', 'engine',
       'type'],
      dtype='object')
CategoricalIndex(['N576AA', 'N557AA', 'N403AA', 'N492AA', 'N262AA', 'N493AA',
                  'N477AA', 'N476AA', 'N504AA', 'N565AA',
                  ...
                  'N472UA', 'N625AW', 'N673AW', 'N629AW', 'N654AW', 'N647AW',
                  'N637AW', 'N676AW', 'N642AW', 'N624AW'],
                 categories=['N10156', 'N10575', 'N11106', 'N11107', ..., 'N997DL', 'N998AT', 'N998DL', 'N999DN'], ordered=False, dtype='category', name='identifier', length=2853)

#### ¿Qué podemos hacer sobre los indices?
* `df.set_axis`: establece el eje, puede funcionar para cambiar el nombre de las columnas
* `df.rename_axis`: renombra el eje 
* `df.rename`: renombra la etiqueta de algún indice (podemos usarlo para cambiar el nombre de las columnas)
* `df.reindex`: reindexa los renglones (cambiando la frecuencia o agregando renglones)

In [36]:
## Ejemplos de lo anterior: 
dta = pd.DataFrame({"A":[1,2,3], "B":[4,5,6]})
print(dta)
print("Cambiamos los indices del defaul a: a,b,c")
print(dta.set_axis(['a','b','c'], axis = 'index'))
print("Cambiamos las columnas de A,B a C y D")
print(dta.set_axis(['C', 'D'], axis = 'columns'))
print("Le ponemos nombre al indice")
print(dta.rename_axis('new_index'))
print("Le cambiamos el nombre a numeros")
print(dta.rename_axis('numeros', axis = 'columns'))
print("Le cambiamos el nombre a las columnas")
print(dta.rename(columns = {'A':'columna_1', 'B':'columna_2'}))

index = ['a', 'b', 'c']
dta2 = pd.DataFrame({"A":[1,2,3], "B":[4,5,6]},index = index)
index_bis = ['a', 'b', 'c', 'd']
dta2.reindex(index_bis)

   A  B
0  1  4
1  2  5
2  3  6
Cambiamos los indices del defaul a: a,b,c
   A  B
a  1  4
b  2  5
c  3  6
Cambiamos las columnas de A,B a C y D
   C  D
0  1  4
1  2  5
2  3  6
Le ponemos nombre al indice
           A  B
new_index
0          1  4
1          2  5
2          3  6
Le cambiamos el nombre a numeros
numeros  A  B
0        1  4
1        2  5
2        3  6
Le cambiamos el nombre a las columnas
   columna_1  columna_2
0          1          4
1          2          5
2          3          6

     A    B
a  1.0  4.0
b  2.0  5.0
c  3.0  6.0
d  NaN  NaN

### EJERCICIO EN CLASE: 
1. Agrega indices al data frame de flights y al de planes
2. Discute con tus companeros por qué el indice que escogiste tiene sentido

### 2. SELECCIONAR

Una de las primeras tareas durante el procesamiento y exploración de datos es la selección de datos. Pandas a través de los DataFrames nos proveen de herramientas para la selección de columnas y registros de manera eficiente.

* Operaciones para seleccionar renglones:
   * `df.loc`
   * `df.iloc`
   * `IndexSlide`
   * `df[mask]`
   * `df.query`
   * `df.sample`

#### 2.1 .loc

In [48]:
# .loc trabaja con los indices
# nos regresa 3 observaciones de la base planes
planes.sample(3)
# Nos regresa el avion con el indice: N937DL
planes.loc['N937DL']
# Nos regresa dos aviones con los indices: 'N708SW' y'N253WN'
planes.loc[['N708SW', 'N253WN']]
# Nos regresa los primeros 3 aviones despues de acomodar los indices
planes.sort_index().head(3)
# Nos regresa todos los indices entre el 'N11106'y el'N11119'
planes.sort_index().loc['N11106':'N11119'] #¡Es cerrado!
# Nos regresa todos los aviones entre N11106 y N11119 pero solo las columnas entre model y speed
planes.sort_index().loc['N11106':'N11119', 'model':'speed']

                model  no.eng  no.seats  speed
identifier
N11106      EMB-145XR     2.0        55    NaN
N11107      EMB-145XR     2.0        55    NaN
N11109      EMB-145XR     2.0        55    NaN
N11113      EMB-145XR     2.0        55    NaN
N11119      EMB-145XR     2.0        55    NaN

#### 2.2 .iloc

In [56]:
# .iloc trabaja con posiciones 
# nos regresa el 3 elemento de la base (el conteo empieza en 0)
planes.iloc[3]
# nos regresa el último elemento de la base planes
planes.iloc[-1]
# nos regresa el elemento 1, el 3 y el 7
planes.iloc[[1,3,7]]
# nos regresa entre el elemento cuatro y el siete!
planes.iloc[4:8]
# nos regresa entre el elemento cuatro y el seis con las columnas 2 y 0
planes.iloc[4:7, [2,0]]
#planes.iloc[2

                     model    year
identifier
N262AA      DC-9-82(MD-82)  1985.0
N493AA      DC-9-82(MD-82)  1989.0
N477AA      DC-9-82(MD-82)  1988.0

#### 2.3 df[mask]

In [69]:
# nos regresa solo la columna year
planes['year']
# nos regresa una serie booleana si se cumple o no la condicion year = 2000
planes['year'] == 2000
# nos regresa todas las observaciones con year = 2000 (158 observaciones)
planes[planes['year'] == 2000]
# nos regresa todas las observaciones con year = 2000 y mfr = AIRBUS INDUSTRIE
planes[(planes['year'] == 2000) & (planes['mfr'] == 'AIRBUS INDUSTRIE')]
# crea una condicion para filtrar los datos
old_planes_mask = planes['year'] < 1990
# filtra de acuerdo a la condición old_places_mask
planes[old_planes_mask]
# selecciona la columna year y filtra todos los aviones con año despues de 1990 
planes.loc[:,'year'].loc[lambda col: col > 1990]

identifier
N576AA    1991.0
N557AA    1993.0
N577AA    1991.0
N552AA    1991.0
N507AA    1997.0
           ...
N472UA    2001.0
N654AW    1999.0
N647AW    1997.0
N676AW    2005.0
N642AW    1996.0
Name: year, Length: 2403, dtype: float64

#### 2.4 filter: filtra usando el indice

In [72]:
# nos quedamos con todos los aviones que en su identifier tienen AA
planes.filter(like = 'AA', axis = 'index')
# nos quedamos con los dos aviones con identifier que conincidan con N492AA y N482AA
planes.filter(regex = 'N492AA|N482AA', axis = 'index')

,year,mfr,model,no.eng,no.seats,speed,engine,type
identifier,,,,,,,,
N492AA,1989.0,MCDONNELL DOUGLAS,DC-9-82(MD-82),2.0,172,NaN,Turbo-fan,Fixed wing multi engine
N482AA,1988.0,MCDONNELL DOUGLAS,DC-9-82(MD-82),2.0,172,NaN,Turbo-fan,Fixed wing multi engine

#### 2.5 query

In [79]:
engines = ['Turbo-shaft', '4 Cycle']
# nos regresa los aviones con engine turbo-shaft y velocidad > 108
planes.query('engine == "Turbo-shaft" and speed > 108')
# nos regresa los aviones con engines en la lista y velocidad > 108
planes.query('engine.isin(@engines) and speed >108')

,year,mfr,model,no.eng,no.seats,speed,engine,type
identifier,,,,,,,,
N515AA,1981.0,BELL,206B,1.0,5,112.0,Turbo-shaft,Rotorcraft
N508AA,1975.0,BELL,206B,1.0,5,112.0,Turbo-shaft,Rotorcraft
N527AA,NaN,BELL,OH-58A,1.0,4,112.0,Turbo-shaft,Rotorcraft

#### OJO: Ciudado con los floating points!!
Prueba el siguiente código: 
`import numpy as np`
`np.sqrt(2)**2 == 2 == 2`   
Discute con tus compañeros que está pasando acá.
¿Cuál crees que sea la solución si tienes que usar floating points? 
`isclose()`, está en la libreria `math()`
Vuelve a correr el codigo pero usa `isclose()` en vez de `==`

In [107]:
import math 
math.isclose(np.sqrt(2)**2,2)

True

### CUIDADO CON LOS MISSING VALUES!
Los missing values son contagiosos

In [108]:
print(np.nan + 10)
print(np.nan/2)
print(np.nan > 25)
print(np.nan == 10)

nan
nan
False
False

En pandas si quieres los missing values tienes que preguntar por ellos explicitamente, de otra manera no los vas a ver cuando filtres

In [115]:
# nos regresa todos los aviones con year missing
planes[planes.year.isnull()]

,year,mfr,model,no.eng,no.seats,speed,engine,type
identifier,,,,,,,,
N504AA,NaN,AUTHIER ANTHONY P,TIERRA II,1.0,2,NaN,Reciprocating,Fixed wing single engine
N555AA,NaN,CESSNA,177A,1.0,4,108.0,Reciprocating,Fixed wing single engine
N531AA,NaN,HARMON ROBERT,FALCON-XP,1.0,2,NaN,Reciprocating,Fixed wing single engine
N512AA,NaN,HARRIS ROLAND W,FALCON XP,1.0,2,NaN,Reciprocating,Fixed wing single engine
N546AA,NaN,AMERICAN AIRCRAFT INC,FALCON XP,1.0,2,NaN,Reciprocating,Fixed wing single engine
...,...,...,...,...,...,...,...,...
N921DN,NaN,MCDONNELL DOUGLAS,MD-90-30,2.0,142,NaN,Turbo-fan,Fixed wing multi engine
N527AS,NaN,BOEING,737-890,2.0,149,NaN,Turbo-fan,Fixed wing multi engine
N922DX,NaN,MCDONNELL DOUGLAS,MD-90-30,2.0,142,NaN,Turbo-fan,Fixed wing multi engine
N924DN,NaN,BOEING,MD-90-30,2.0,142,NaN,Turbo-fan,Fixed wing multi engine
N673AW,NaN,AIRBUS,A320-232,2.0,200,NaN,Turbo-fan,Fixed wing multi engine

### 3. FUNCIONES DE AGREGACIÓN
 Previamente, hemos explorado como seleccionar datos que son relevantes de un DataFrame o Series. Sin embargo, en ocasiones se necesitan hacer agregaciones para poder obtener insights a partir de los datos. 
 
#### 3.1 Funciones Resumen
Pandas posee funciones de resumen estadístico los cuales permiten acceder a métricas de estadistica descriptiva. El método describe() provee un resumen estadístico de los atributos en una columna dada o las columnas en un DataFrame. Observa que se tienen resultados diferentes en caso que la columna sea numérica o categórica.

In [116]:
# con todo el data set nos regresa solo el resumen de las variables numéricas
planes.describe()

              year       no.eng     no.seats       speed
count  2761.000000  2851.000000  2853.000000   59.000000
mean   1999.288664     1.981761   134.315457  305.440678
std       7.101973     0.148739    62.125947  160.933406
min    1946.000000     1.000000     1.000000   60.000000
25%    1995.000000     2.000000    80.000000  114.000000
50%    2001.000000     2.000000   145.000000  432.000000
75%    2004.000000     2.000000   172.000000  432.000000
max    2013.000000     4.000000   442.000000  435.000000

In [117]:
# variable numérica
planes.speed.describe()

count     59.000000
mean     305.440678
std      160.933406
min       60.000000
25%      114.000000
50%      432.000000
75%      432.000000
max      435.000000
Name: speed, dtype: float64

In [119]:
# variables categóricas
planes.mfr.describe()

count       2853
unique        53
top       BOEING
freq        1300
Name: mfr, dtype: object

Si se desea obtener algun resultado estadístico particular de una columna es probable que exista un método asociado. Por ejemplo, si queremos obtener el año promedio, el más antiguo y reciente en que se dieron de alta las unidades económicas en el conjunto provisto, podemos aplicar las siguientes sentencias.

In [121]:
print(planes.speed.mean())
print(planes.year.min())
print(planes.year.max())

305.4406779661017
1946.0
2013.0

Los elementos anteriores permiten obtener agregaciones con variables numéricas. Sin embargo, en el caso de las categóricas, también se poseen métodos como `nunique()`, `unique()` y `values_counts()` que resultan útiles en el proceso de exploración.

In [123]:
print(planes.type.nunique())
print(planes.type.unique())
print(planes.type.value_counts())

5
['Fixed wing multi engine' 'Fixed wing single engine' 'Balloon'
 'Rotorcraft' 'Weight-shift-control']
Fixed wing multi engine     2794
Fixed wing single engine      49
Rotorcraft                     7
Balloon                        2
Weight-shift-control           1
Name: type, dtype: int64

La siguiente table muestra las agregaciones incluidas en Pandas:

|Aggregation|	Description|
|---|---|
|count()|	Total number of items|
|first(), last()|	First and last item|
|mean(), median()|	Mean and median|
|min(), max()|	Minimum and maximum|
|std(), var()|	Standard deviation and variance|
|mad()|	Mean absolute deviation|
|prod()|	Product of all items|
|sum()|	Sum of all items|


Todos los anteriores son métodos tanto para DataFrames como para Series.

### 4. Operaciones con una sola fuente de datos 
1. `.agg` agregar sobre alguno de los ejes

In [135]:
# para una sola variable
planes['speed'].agg(['mean','max'])
# para varias variables
planes.agg({'speed':['mean', 'max'], 'year':['max','min']})

           speed    year
mean  305.440678     NaN
max   435.000000  2013.0
min          NaN  1946.0

2. `.transform` no cambia el tamaño del dataframe si empezamos con n renglones terminamos con n renglones

In [136]:
# Por ejemplo: si queremos saber la edad de los aviones 
planes.year.transform(lambda x: 2023 - x)

identifier
N576AA    32.0
N557AA    30.0
N403AA    49.0
N492AA    34.0
N262AA    38.0
          ...
N647AW    26.0
N637AW    33.0
N676AW    18.0
N642AW    27.0
N624AW    34.0
Name: year, Length: 2853, dtype: float64

3. `.apply` aplica una función a lo largo de un eje y transforma el dataframe a cualquier tamaño

In [143]:
def plane_size(number):
    if number > 80:
        return 'large'
    return 'small'

planes['no.seats'].apply(plane_size)

identifier
N576AA    large
N557AA    small
N403AA    small
N492AA    large
N262AA    large
          ...
N647AW    large
N637AW    large
N676AW    large
N642AW    large
N624AW    large
Name: no.seats, Length: 2853, dtype: object

**Ojo:** apply y transform se parecen pero no son iguales

`transform`
   * puede recibir una funcion, una string function, una lista de funciones y un diccionario
   * no puede producir resultados agregados (si le das n renglones, regresa n renglones)
   * solo puede trabajar con una Serie 
   
`apply`
   * solo puede recibir funciones
   * puede producir resultados agregados (le das n renglones, puede regresar <n reglones)
   * puede trabajar con muchas series al mismo tiempo

Estructura de estas operaciones 
1. `Dataframe.operacion(args)`
2. Siempre regresean una Serie o un DataFrame nuevo
3. Por default nunca modifica, si quieres que modifique necesitas:
     * `inplace = True`
     *  assignar tu operacion a una nueva columna o dataframe

### EJERCICIO EN CLASE: 
Encuentra todos los vuelos con las siguientes características (de la base de `flights`)
1. Hacia **SFO** o **OAK**
2. En enero
3. Retrasados por más de una hora 
4. Que despegaron entre las 12 de la noche y las 5 de la mañana (red-eye)
5. Donde el retraso de llegada fue más del doble que el retraso de despegue
6. Con `dep_time` faltante. ¿Qué otras variables le faltan a estos vuelos? ¿Por qué?

### 4.Agrupaciones, Ordenamiento y Mutaciones

#### 4.1 Ordenamiento

In [151]:
planes.sort_values(by = 'year')
planes.sort_values(by = 'year', ascending=False)

,year,mfr,model,no.eng,no.seats,speed,engine,type
identifier,,,,,,,,
N126AT,2013.0,SEA & SKY INC,CYGNET,1.0,2,NaN,4 Cycle,Weight-shift-control
N537JB,2012.0,ROBINSON HELICOPTER CO,R66,1.0,6,NaN,Turbo-shaft,Rotorcraft
N955WN,2011.0,BOEING,737-7H4,2.0,140,NaN,Turbo-fan,Fixed wing multi engine
N73445,2011.0,BOEING,737-924ER,2.0,191,NaN,Turbo-fan,Fixed wing multi engine
N958WN,2011.0,BOEING,737-7H4,2.0,140,NaN,Turbo-fan,Fixed wing multi engine
...,...,...,...,...,...,...,...,...
N921DN,NaN,MCDONNELL DOUGLAS,MD-90-30,2.0,142,NaN,Turbo-fan,Fixed wing multi engine
N527AS,NaN,BOEING,737-890,2.0,149,NaN,Turbo-fan,Fixed wing multi engine
N922DX,NaN,MCDONNELL DOUGLAS,MD-90-30,2.0,142,NaN,Turbo-fan,Fixed wing multi engine
N924DN,NaN,BOEING,MD-90-30,2.0,142,NaN,Turbo-fan,Fixed wing multi engine
N673AW,NaN,AIRBUS,A320-232,2.0,200,NaN,Turbo-fan,Fixed wing multi engine

**¿Qué esta pasando con los missings cuando ordenamos?**

### EJERCICIO EXTRA:
* Ordena los vuelos por fecha de partida y hora
* ¿Qué vuelos son los más retrasados?
* ¿Qué vuelos duraron más?

#### 4.2 Mutar 
Si quieres crear nuevas columnas puedes:
    1. Usar `.transform` o `.apply` 
    2. Usar otras columnas para crear nuevas

In [156]:
# Por ejemplo si queremos una columna que os diga si un avion tiene más de un motor 
planes['no.eng'] > 1

identifier
N576AA     True
N557AA    False
N403AA    False
N492AA     True
N262AA     True
          ...
N647AW     True
N637AW     True
N676AW     True
N642AW     True
N624AW     True
Name: no.eng, Length: 2853, dtype: bool

#### EJERCICIO EN CLASE:
1. Calcula la velocidad `mph` usando la columna de `time` y `dist`. ¿Cuál fue el vuelo más rápido?
2. Agrega una nueva variable que muestre cuanto tiempo se gano o se perdio en cada vuelo

#### 4.3 Agrupaciones

Algunas veces quieres calcular algo como `z = (x - mean(x))/sd(x)`

* Queremos encontrar que tan rápido van los aviones por tipo de motor. 
* ¿Qué necesitamos hacer para contestar esta pregunta?
    * Agrupar los aviones por tipo de motor 
    * Sacar la media de la velocidad por cada tipo de motor 
* ¿Cómo hacemos esto? `groupby()`

In [157]:
# primero agrupamos por motor, le indicamos que variable nos interes (speed) y 
# sacamos lo que queremos en este caso la media
# Ojo: siempre nos va a regresar una serie
planes.groupby('engine')['speed'].mean()

engine
4 Cycle          108.000000
None              60.000000
Reciprocating    109.875000
Turbo-fan        429.000000
Turbo-jet        432.085714
Turbo-prop       147.000000
Turbo-shaft      112.000000
Name: speed, dtype: float64

* `groupby` proviene de un comando en el lenguaje de base de datos SQL
* Quizás sea más esclarecedor pensar en él en los términos acuñados por primera vez por Hadley Wickham: dividir (split), aplicar (apply), combinar (combine).
* Observa la siguiente imagen:
![GroupBy](https://jakevdp.github.io/PythonDataScienceHandbook/figures/03.08-split-apply-combine.png)

El agrupamiento ocurre como sigue:

* El paso de división implica dividir y agrupar un DataFrame según el valor de la clave especificada.
* El paso de aplicación implica calcular alguna función, generalmente un agregado, transformación o filtrado, dentro de los grupos individuales.
* El paso de combinación combina los resultados de estas operaciones en una matriz de salida.

#### 4.4 Agrupaciones con agregaciones

Por ejemplo si queremos encontrar cuanto se retrasan los vuelos por compañia

In [160]:
flights.groupby('carrier')['dep_delay'].agg(['mean', 'min', 'max'])

              mean   min    max
carrier
AA        6.390144 -15.0  970.0
AS        3.712329 -15.0  172.0
B6       13.320532 -14.0  310.0
CO        9.261313 -18.0  981.0
DL        9.370627 -17.0  730.0
EV       12.482193 -18.0  479.0
F9        5.093637 -15.0  275.0
FL        4.716376 -14.0  507.0
MQ       11.071745 -23.0  931.0
OO        8.885482 -33.0  360.0
UA       12.918707 -11.0  869.0
US        1.622926 -17.0  425.0
WN       13.488241 -10.0  548.0
XE        7.713728 -19.0  628.0
YV        1.538462 -11.0   54.0

 En el caso anterior, hemos indicado una lista con las agregaciones deseadas. Sin embargo, también es posible pasar un diccionario con el nombre de las columnas, y las operaciones a ser aplicadas.

In [164]:
# ¿Qué estamos calculando acá?
flights.groupby('carrier').agg({'dep_delay':['mean','min','max'],
                               'dest':'nunique'})

         dep_delay                 dest
              mean   min    max nunique
carrier
AA        6.390144 -15.0  970.0       2
AS        3.712329 -15.0  172.0       1
B6       13.320532 -14.0  310.0       1
CO        9.261313 -18.0  981.0      62
DL        9.370627 -17.0  730.0       3
EV       12.482193 -18.0  479.0       5
F9        5.093637 -15.0  275.0       2
FL        4.716376 -14.0  507.0       2
MQ       11.071745 -23.0  931.0       3
OO        8.885482 -33.0  360.0      34
UA       12.918707 -11.0  869.0       6
US        1.622926 -17.0  425.0       3
WN       13.488241 -10.0  548.0      33
XE        7.713728 -19.0  628.0      81
YV        1.538462 -11.0   54.0       3

In [162]:
flights.columns

Index(['date', 'hour', 'minute', 'dep', 'arr', 'dep_delay', 'arr_delay',
       'carrier', 'flight', 'dest', 'plane', 'cancelled', 'time', 'dist'],
      dtype='object')

### PIPES: 

* Matematicamente vienen de la función composición: f ◦ g = f (g(x ))
* La mayoría de los lenguajes de programación la tiene:
    * terminal |
    * R %>%
    * Python pipe() o () (en pandas)
    
Corre el siguiete código y explica que es lo que esta pasando:

In [165]:
flights.groupby('dest').agg(
    count = ('dist', 'size'),
    dist = ('dist', 'mean'),
    delay = ('arr_delay', 'mean')).query('count > 20 & dest != "HNL"')

      count         dist      delay
dest
ABQ    2812   749.435633   7.226259
AEX     724   190.000000   5.839437
AMA    1297   517.996145   6.840095
ANC     125  3266.000000  26.080645
ASE     125   913.728000   6.794643
...     ...          ...        ...
TUL    2924   437.774282   6.351710
TUS    1565   936.000000   7.801680
TYS    1210   771.480165  11.365915
VPS     880   528.000000  12.457176
XNA    1172   438.000000   6.896277

[113 rows x 3 columns]

### EJERCICIO EN CLASE:
usando pipes responde lo siguiente
1. ¿Qué destinos tienen el promedio más alto de retrasos?
2. ¿Qué vuelos (`carrier + flight`) suceda cada día? ¿Hacia dónde vuelan?
3. En promedio, ¿Qué aviones se retrasan más?